title: "Demian Banakh"
email: "demian.banakh@doctoral.uj.edu.pl"
description: "PhD student in TCS"
baseurl: "" # leave empty since this is a user site
url: "https://dembanakh.github.io"

# Use Minimal Mistakes remote theme
remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: "aqua"

plugins:
  - jekyll-include-cache

author:
  name: "Demian Banakh"
  bio: "PhD student in TCS"
  location: "Jagiellonian University, Poland"
  links:
    - label: "name.surname at doctoral.uj.edu.pl"
      icon: "fas fa-envelope"
      url: ""

show_recent_posts: false

include:
  - _pages

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      show_date: true
      date_format: "%-d %b"
  - scope:
      path: ""
    values:
      custom_css: "/assets/css/custom.scss"

sass:
  style: compressed


