title: "Demian Banakh"
email: "demian.banakh@doctoral.uj.edu.pl"
description: "PhD student in TCS"
baseurl: "" # leave empty since this is a user site
url: "https://dembanakh.github.io"

# Use Minimal Mistakes remote theme
remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: "aqua"

plugins:
  - jekyll-include-cache

author:
  name: ""
  bio: "PhD student in TCS"
  location: "Jagiellonian University, Poland"
  links:
    - label: "name.surname at doctoral.uj.edu.pl"
      icon: "fas fa-envelope"
      url: ""

locale: en
recent_posts_title: "Recent"

include:
  - _pages

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      show_date: true
      date_format: "%-d %b"

sass:
  style: compressed


